### ISSUE TITLE
No python3 entirely

### ISSUE THREAD

**Issue by gusarg81** [ricardochaves/python3-sdk#1]
This is not python3 entirely port... You should re-recheck module imports and python3 syntax. Some fixes:
- Imports:

from configparser import SafeConfigParser
...
from urllib.parse import urlencode
- Exception:

...
raise Exception("Offline-Access is not allowed.")

**Comment by ricardochaves** [comment]
Sorry about that. Up the fixes now. [Commit](https://github.com/ricardochaves/python3-sdk/commit/04038f31b314c675d452ca5025a0ad9e7d9ba6f9)
